# Generated by Django 5.1.5 on 2025-02-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('difficulty', models.CharField(max_length=2)),
                ('examboard', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deck',
            name='topic',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.CharField(max_length=20),
        ),
    ]
