# Generated by Django 5.1.5 on 2025-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pastquestions_alter_deck_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastquestions',
            name='answer',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pastquestions',
            name='question',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
