# Generated by Django 5.1.5 on 2025-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pastquestions_answer_pastquestions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastquestions',
            name='marks',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pastquestions',
            name='timereq',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
