# Generated by Django 5.1.5 on 2025-02-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='systemLang',
            field=models.CharField(max_length=15),
        ),
    ]
